%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.3

-ifndef(common_pb).
-define(common_pb, true).

-define(common_pb_gpb_version, "4.1.3").

-ifndef('WORLDRESP_PB_H').
-define('WORLDRESP_PB_H', true).
-record(worldResp,
        {msg                    :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('HELLOREQ_PB_H').
-define('HELLOREQ_PB_H', true).
-record(helloReq,
        {msg                    :: iodata() | undefined % = 1
        }).
-endif.

-endif.
