%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.6
-module(common_pb).

-export([encode_msg/1, encode_msg/2]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3]).
-export([verify_msg/1, verify_msg/2]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([enum_symbol_by_value_LOGINMSG/1, enum_value_by_symbol_LOGINMSG/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("common_pb.hrl").
-include("gpb.hrl").

%% enumerated types
-type 'LOGINMSG'() :: 'SUCCESED' | 'FAILED' | 'NOTFOUND'.
-export_type(['LOGINMSG'/0]).

%% message types
-type loginResp() :: #loginResp{}.
-type worldResp() :: #worldResp{}.
-type loginReq() :: #loginReq{}.
-type helloReq() :: #helloReq{}.
-type heartbeatResp() :: #heartbeatResp{}.
-type heartbeatReq() :: #heartbeatReq{}.
-export_type(['loginResp'/0, 'worldResp'/0, 'loginReq'/0, 'helloReq'/0, 'heartbeatResp'/0, 'heartbeatReq'/0]).

-spec encode_msg(#loginResp{} | #worldResp{} | #loginReq{} | #helloReq{} | #heartbeatResp{} | #heartbeatReq{}) -> binary().
encode_msg(Msg) -> encode_msg(Msg, []).


-spec encode_msg(#loginResp{} | #worldResp{} | #loginReq{} | #helloReq{} | #heartbeatResp{} | #heartbeatReq{}, list()) -> binary().
encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #loginResp{} -> e_msg_loginResp(Msg, TrUserData);
      #worldResp{} -> e_msg_worldResp(Msg, TrUserData);
      #loginReq{} -> e_msg_loginReq(Msg, TrUserData);
      #helloReq{} -> e_msg_helloReq(Msg, TrUserData);
      #heartbeatResp{} ->
	  e_msg_heartbeatResp(Msg, TrUserData);
      #heartbeatReq{} -> e_msg_heartbeatReq(Msg, TrUserData)
    end.



e_msg_loginResp(Msg, TrUserData) ->
    e_msg_loginResp(Msg, <<>>, TrUserData).


e_msg_loginResp(#loginResp{result = F1, user_id = F2,
			   user_name = F3},
		Bin, TrUserData) ->
    B1 = begin
	   TrF1 = id(F1, TrUserData),
	   e_enum_LOGINMSG(TrF1, <<Bin/binary, 8>>)
	 end,
    B2 = if F2 == undefined -> B1;
	    true ->
		begin
		  TrF2 = id(F2, TrUserData),
		  e_varint(TrF2, <<B1/binary, 16>>)
		end
	 end,
    if F3 == undefined -> B2;
       true ->
	   begin
	     TrF3 = id(F3, TrUserData),
	     e_type_string(TrF3, <<B2/binary, 26>>)
	   end
    end.

e_msg_worldResp(Msg, TrUserData) ->
    e_msg_worldResp(Msg, <<>>, TrUserData).


e_msg_worldResp(#worldResp{msg = F1}, Bin,
		TrUserData) ->
    if F1 == undefined -> Bin;
       true ->
	   begin
	     TrF1 = id(F1, TrUserData),
	     e_type_string(TrF1, <<Bin/binary, 10>>)
	   end
    end.

e_msg_loginReq(Msg, TrUserData) ->
    e_msg_loginReq(Msg, <<>>, TrUserData).


e_msg_loginReq(#loginReq{cookie = F1}, Bin,
	       TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_type_string(TrF1, <<Bin/binary, 10>>)
    end.

e_msg_helloReq(Msg, TrUserData) ->
    e_msg_helloReq(Msg, <<>>, TrUserData).


e_msg_helloReq(#helloReq{msg = F1}, Bin, TrUserData) ->
    if F1 == undefined -> Bin;
       true ->
	   begin
	     TrF1 = id(F1, TrUserData),
	     e_type_string(TrF1, <<Bin/binary, 10>>)
	   end
    end.

e_msg_heartbeatResp(Msg, TrUserData) ->
    e_msg_heartbeatResp(Msg, <<>>, TrUserData).


e_msg_heartbeatResp(#heartbeatResp{unixtime = F1}, Bin,
		    TrUserData) ->
    if F1 == undefined -> Bin;
       true ->
	   begin
	     TrF1 = id(F1, TrUserData),
	     e_varint(TrF1, <<Bin/binary, 8>>)
	   end
    end.

e_msg_heartbeatReq(_Msg, _TrUserData) -> <<>>.

e_enum_LOGINMSG('SUCCESED', Bin) -> <<Bin/binary, 1>>;
e_enum_LOGINMSG('FAILED', Bin) -> <<Bin/binary, 2>>;
e_enum_LOGINMSG('NOTFOUND', Bin) -> <<Bin/binary, 3>>;
e_enum_LOGINMSG(V, Bin) -> e_varint(V, Bin).

e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('GPB_PATTERN_STACK').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(loginResp, Bin, TrUserData) ->
    d_msg_loginResp(Bin, TrUserData);
decode_msg_2_doit(worldResp, Bin, TrUserData) ->
    d_msg_worldResp(Bin, TrUserData);
decode_msg_2_doit(loginReq, Bin, TrUserData) ->
    d_msg_loginReq(Bin, TrUserData);
decode_msg_2_doit(helloReq, Bin, TrUserData) ->
    d_msg_helloReq(Bin, TrUserData);
decode_msg_2_doit(heartbeatResp, Bin, TrUserData) ->
    d_msg_heartbeatResp(Bin, TrUserData);
decode_msg_2_doit(heartbeatReq, Bin, TrUserData) ->
    d_msg_heartbeatReq(Bin, TrUserData).



d_msg_loginResp(Bin, TrUserData) ->
    dfp_read_field_def_loginResp(Bin, 0, 0,
				 id(undefined, TrUserData),
				 id(undefined, TrUserData),
				 id(undefined, TrUserData), TrUserData).

dfp_read_field_def_loginResp(<<8, Rest/binary>>, Z1, Z2,
			     F@_1, F@_2, F@_3, TrUserData) ->
    d_field_loginResp_result(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			     TrUserData);
dfp_read_field_def_loginResp(<<16, Rest/binary>>, Z1,
			     Z2, F@_1, F@_2, F@_3, TrUserData) ->
    d_field_loginResp_user_id(Rest, Z1, Z2, F@_1, F@_2,
			      F@_3, TrUserData);
dfp_read_field_def_loginResp(<<26, Rest/binary>>, Z1,
			     Z2, F@_1, F@_2, F@_3, TrUserData) ->
    d_field_loginResp_user_name(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, TrUserData);
dfp_read_field_def_loginResp(<<>>, 0, 0, F@_1, F@_2,
			     F@_3, _) ->
    #loginResp{result = F@_1, user_id = F@_2,
	       user_name = F@_3};
dfp_read_field_def_loginResp(Other, Z1, Z2, F@_1, F@_2,
			     F@_3, TrUserData) ->
    dg_read_field_def_loginResp(Other, Z1, Z2, F@_1, F@_2,
				F@_3, TrUserData).

dg_read_field_def_loginResp(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_loginResp(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_loginResp(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_loginResp_result(Rest, 0, 0, F@_1, F@_2, F@_3,
				   TrUserData);
      16 ->
	  d_field_loginResp_user_id(Rest, 0, 0, F@_1, F@_2, F@_3,
				    TrUserData);
      26 ->
	  d_field_loginResp_user_name(Rest, 0, 0, F@_1, F@_2,
				      F@_3, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_loginResp(Rest, 0, 0, F@_1, F@_2, F@_3,
				      TrUserData);
	    1 ->
		skip_64_loginResp(Rest, 0, 0, F@_1, F@_2, F@_3,
				  TrUserData);
	    2 ->
		skip_length_delimited_loginResp(Rest, 0, 0, F@_1, F@_2,
						F@_3, TrUserData);
	    3 ->
		skip_group_loginResp(Rest, Key bsr 3, 0, F@_1, F@_2,
				     F@_3, TrUserData);
	    5 ->
		skip_32_loginResp(Rest, 0, 0, F@_1, F@_2, F@_3,
				  TrUserData)
	  end
    end;
dg_read_field_def_loginResp(<<>>, 0, 0, F@_1, F@_2,
			    F@_3, _) ->
    #loginResp{result = F@_1, user_id = F@_2,
	       user_name = F@_3}.

d_field_loginResp_result(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_loginResp_result(Rest, N + 7, X bsl N + Acc,
			     F@_1, F@_2, F@_3, TrUserData);
d_field_loginResp_result(<<0:1, X:7, Rest/binary>>, N,
			 Acc, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = {d_enum_LOGINMSG(begin
					    <<Res:32/signed-native>> = <<(X bsl
									    N
									    +
									    Acc):32/unsigned-native>>,
					    Res
					  end),
			  Rest},
    dfp_read_field_def_loginResp(RestF, 0, 0, NewFValue,
				 F@_2, F@_3, TrUserData).

d_field_loginResp_user_id(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_loginResp_user_id(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, F@_3, TrUserData);
d_field_loginResp_user_id(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = {X bsl N + Acc, Rest},
    dfp_read_field_def_loginResp(RestF, 0, 0, F@_1,
				 NewFValue, F@_3, TrUserData).

d_field_loginResp_user_name(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_loginResp_user_name(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, TrUserData);
d_field_loginResp_user_name(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_loginResp(RestF, 0, 0, F@_1, F@_2,
				 NewFValue, TrUserData).

skip_varint_loginResp(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		      F@_1, F@_2, F@_3, TrUserData) ->
    skip_varint_loginResp(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			  TrUserData);
skip_varint_loginResp(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		      F@_1, F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_loginResp(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, TrUserData).

skip_length_delimited_loginResp(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    skip_length_delimited_loginResp(Rest, N + 7,
				    X bsl N + Acc, F@_1, F@_2, F@_3,
				    TrUserData);
skip_length_delimited_loginResp(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_loginResp(Rest2, 0, 0, F@_1, F@_2,
				 F@_3, TrUserData).

skip_group_loginResp(Bin, FNum, Z2, F@_1, F@_2, F@_3,
		     TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_loginResp(Rest, 0, Z2, F@_1, F@_2,
				 F@_3, TrUserData).

skip_32_loginResp(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		  F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_loginResp(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, TrUserData).

skip_64_loginResp(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		  F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_loginResp(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, TrUserData).

d_msg_worldResp(Bin, TrUserData) ->
    dfp_read_field_def_worldResp(Bin, 0, 0,
				 id(undefined, TrUserData), TrUserData).

dfp_read_field_def_worldResp(<<10, Rest/binary>>, Z1,
			     Z2, F@_1, TrUserData) ->
    d_field_worldResp_msg(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_worldResp(<<>>, 0, 0, F@_1, _) ->
    #worldResp{msg = F@_1};
dfp_read_field_def_worldResp(Other, Z1, Z2, F@_1,
			     TrUserData) ->
    dg_read_field_def_worldResp(Other, Z1, Z2, F@_1,
				TrUserData).

dg_read_field_def_worldResp(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_worldResp(Rest, N + 7, X bsl N + Acc,
				F@_1, TrUserData);
dg_read_field_def_worldResp(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_worldResp_msg(Rest, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_worldResp(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_worldResp(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_worldResp(Rest, 0, 0, F@_1,
						TrUserData);
	    3 ->
		skip_group_worldResp(Rest, Key bsr 3, 0, F@_1,
				     TrUserData);
	    5 -> skip_32_worldResp(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_worldResp(<<>>, 0, 0, F@_1, _) ->
    #worldResp{msg = F@_1}.

d_field_worldResp_msg(<<1:1, X:7, Rest/binary>>, N, Acc,
		      F@_1, TrUserData)
    when N < 57 ->
    d_field_worldResp_msg(Rest, N + 7, X bsl N + Acc, F@_1,
			  TrUserData);
d_field_worldResp_msg(<<0:1, X:7, Rest/binary>>, N, Acc,
		      _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_worldResp(RestF, 0, 0, NewFValue,
				 TrUserData).

skip_varint_worldResp(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		      F@_1, TrUserData) ->
    skip_varint_worldResp(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_worldResp(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		      F@_1, TrUserData) ->
    dfp_read_field_def_worldResp(Rest, Z1, Z2, F@_1,
				 TrUserData).

skip_length_delimited_worldResp(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_worldResp(Rest, N + 7,
				    X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_worldResp(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_worldResp(Rest2, 0, 0, F@_1,
				 TrUserData).

skip_group_worldResp(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_worldResp(Rest, 0, Z2, F@_1,
				 TrUserData).

skip_32_worldResp(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		  TrUserData) ->
    dfp_read_field_def_worldResp(Rest, Z1, Z2, F@_1,
				 TrUserData).

skip_64_worldResp(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		  TrUserData) ->
    dfp_read_field_def_worldResp(Rest, Z1, Z2, F@_1,
				 TrUserData).

d_msg_loginReq(Bin, TrUserData) ->
    dfp_read_field_def_loginReq(Bin, 0, 0,
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_loginReq(<<10, Rest/binary>>, Z1, Z2,
			    F@_1, TrUserData) ->
    d_field_loginReq_cookie(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_loginReq(<<>>, 0, 0, F@_1, _) ->
    #loginReq{cookie = F@_1};
dfp_read_field_def_loginReq(Other, Z1, Z2, F@_1,
			    TrUserData) ->
    dg_read_field_def_loginReq(Other, Z1, Z2, F@_1,
			       TrUserData).

dg_read_field_def_loginReq(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_loginReq(Rest, N + 7, X bsl N + Acc,
			       F@_1, TrUserData);
dg_read_field_def_loginReq(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_loginReq_cookie(Rest, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_loginReq(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_loginReq(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_loginReq(Rest, 0, 0, F@_1,
					       TrUserData);
	    3 ->
		skip_group_loginReq(Rest, Key bsr 3, 0, F@_1,
				    TrUserData);
	    5 -> skip_32_loginReq(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_loginReq(<<>>, 0, 0, F@_1, _) ->
    #loginReq{cookie = F@_1}.

d_field_loginReq_cookie(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_loginReq_cookie(Rest, N + 7, X bsl N + Acc,
			    F@_1, TrUserData);
d_field_loginReq_cookie(<<0:1, X:7, Rest/binary>>, N,
			Acc, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_loginReq(RestF, 0, 0, NewFValue,
				TrUserData).

skip_varint_loginReq(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    skip_varint_loginReq(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_loginReq(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    dfp_read_field_def_loginReq(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_length_delimited_loginReq(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_loginReq(Rest, N + 7,
				   X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_loginReq(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_loginReq(Rest2, 0, 0, F@_1,
				TrUserData).

skip_group_loginReq(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_loginReq(Rest, 0, Z2, F@_1,
				TrUserData).

skip_32_loginReq(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_loginReq(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_64_loginReq(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_loginReq(Rest, Z1, Z2, F@_1,
				TrUserData).

d_msg_helloReq(Bin, TrUserData) ->
    dfp_read_field_def_helloReq(Bin, 0, 0,
				id(undefined, TrUserData), TrUserData).

dfp_read_field_def_helloReq(<<10, Rest/binary>>, Z1, Z2,
			    F@_1, TrUserData) ->
    d_field_helloReq_msg(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_helloReq(<<>>, 0, 0, F@_1, _) ->
    #helloReq{msg = F@_1};
dfp_read_field_def_helloReq(Other, Z1, Z2, F@_1,
			    TrUserData) ->
    dg_read_field_def_helloReq(Other, Z1, Z2, F@_1,
			       TrUserData).

dg_read_field_def_helloReq(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_helloReq(Rest, N + 7, X bsl N + Acc,
			       F@_1, TrUserData);
dg_read_field_def_helloReq(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_helloReq_msg(Rest, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_helloReq(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_helloReq(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_helloReq(Rest, 0, 0, F@_1,
					       TrUserData);
	    3 ->
		skip_group_helloReq(Rest, Key bsr 3, 0, F@_1,
				    TrUserData);
	    5 -> skip_32_helloReq(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_helloReq(<<>>, 0, 0, F@_1, _) ->
    #helloReq{msg = F@_1}.

d_field_helloReq_msg(<<1:1, X:7, Rest/binary>>, N, Acc,
		     F@_1, TrUserData)
    when N < 57 ->
    d_field_helloReq_msg(Rest, N + 7, X bsl N + Acc, F@_1,
			 TrUserData);
d_field_helloReq_msg(<<0:1, X:7, Rest/binary>>, N, Acc,
		     _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Bytes:Len/binary, Rest2/binary>> = Rest,
			   {binary:copy(Bytes), Rest2}
			 end,
    dfp_read_field_def_helloReq(RestF, 0, 0, NewFValue,
				TrUserData).

skip_varint_helloReq(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    skip_varint_helloReq(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_helloReq(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    dfp_read_field_def_helloReq(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_length_delimited_helloReq(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_helloReq(Rest, N + 7,
				   X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_helloReq(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_helloReq(Rest2, 0, 0, F@_1,
				TrUserData).

skip_group_helloReq(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_helloReq(Rest, 0, Z2, F@_1,
				TrUserData).

skip_32_helloReq(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_helloReq(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_64_helloReq(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_helloReq(Rest, Z1, Z2, F@_1,
				TrUserData).

d_msg_heartbeatResp(Bin, TrUserData) ->
    dfp_read_field_def_heartbeatResp(Bin, 0, 0,
				     id(undefined, TrUserData), TrUserData).

dfp_read_field_def_heartbeatResp(<<8, Rest/binary>>, Z1,
				 Z2, F@_1, TrUserData) ->
    d_field_heartbeatResp_unixtime(Rest, Z1, Z2, F@_1,
				   TrUserData);
dfp_read_field_def_heartbeatResp(<<>>, 0, 0, F@_1, _) ->
    #heartbeatResp{unixtime = F@_1};
dfp_read_field_def_heartbeatResp(Other, Z1, Z2, F@_1,
				 TrUserData) ->
    dg_read_field_def_heartbeatResp(Other, Z1, Z2, F@_1,
				    TrUserData).

dg_read_field_def_heartbeatResp(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_heartbeatResp(Rest, N + 7,
				    X bsl N + Acc, F@_1, TrUserData);
dg_read_field_def_heartbeatResp(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_heartbeatResp_unixtime(Rest, 0, 0, F@_1,
					 TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_heartbeatResp(Rest, 0, 0, F@_1, TrUserData);
	    1 ->
		skip_64_heartbeatResp(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_heartbeatResp(Rest, 0, 0, F@_1,
						    TrUserData);
	    3 ->
		skip_group_heartbeatResp(Rest, Key bsr 3, 0, F@_1,
					 TrUserData);
	    5 -> skip_32_heartbeatResp(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_heartbeatResp(<<>>, 0, 0, F@_1, _) ->
    #heartbeatResp{unixtime = F@_1}.

d_field_heartbeatResp_unixtime(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_heartbeatResp_unixtime(Rest, N + 7,
				   X bsl N + Acc, F@_1, TrUserData);
d_field_heartbeatResp_unixtime(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, _, TrUserData) ->
    {NewFValue, RestF} = {X bsl N + Acc, Rest},
    dfp_read_field_def_heartbeatResp(RestF, 0, 0, NewFValue,
				     TrUserData).

skip_varint_heartbeatResp(<<1:1, _:7, Rest/binary>>, Z1,
			  Z2, F@_1, TrUserData) ->
    skip_varint_heartbeatResp(Rest, Z1, Z2, F@_1,
			      TrUserData);
skip_varint_heartbeatResp(<<0:1, _:7, Rest/binary>>, Z1,
			  Z2, F@_1, TrUserData) ->
    dfp_read_field_def_heartbeatResp(Rest, Z1, Z2, F@_1,
				     TrUserData).

skip_length_delimited_heartbeatResp(<<1:1, X:7,
				      Rest/binary>>,
				    N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_heartbeatResp(Rest, N + 7,
					X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_heartbeatResp(<<0:1, X:7,
				      Rest/binary>>,
				    N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_heartbeatResp(Rest2, 0, 0, F@_1,
				     TrUserData).

skip_group_heartbeatResp(Bin, FNum, Z2, F@_1,
			 TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_heartbeatResp(Rest, 0, Z2, F@_1,
				     TrUserData).

skip_32_heartbeatResp(<<_:32, Rest/binary>>, Z1, Z2,
		      F@_1, TrUserData) ->
    dfp_read_field_def_heartbeatResp(Rest, Z1, Z2, F@_1,
				     TrUserData).

skip_64_heartbeatResp(<<_:64, Rest/binary>>, Z1, Z2,
		      F@_1, TrUserData) ->
    dfp_read_field_def_heartbeatResp(Rest, Z1, Z2, F@_1,
				     TrUserData).

d_msg_heartbeatReq(Bin, TrUserData) ->
    dfp_read_field_def_heartbeatReq(Bin, 0, 0, TrUserData).

dfp_read_field_def_heartbeatReq(<<>>, 0, 0, _) ->
    #heartbeatReq{};
dfp_read_field_def_heartbeatReq(Other, Z1, Z2,
				TrUserData) ->
    dg_read_field_def_heartbeatReq(Other, Z1, Z2,
				   TrUserData).

dg_read_field_def_heartbeatReq(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_heartbeatReq(Rest, N + 7,
				   X bsl N + Acc, TrUserData);
dg_read_field_def_heartbeatReq(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
      0 -> skip_varint_heartbeatReq(Rest, 0, 0, TrUserData);
      1 -> skip_64_heartbeatReq(Rest, 0, 0, TrUserData);
      2 ->
	  skip_length_delimited_heartbeatReq(Rest, 0, 0,
					     TrUserData);
      3 ->
	  skip_group_heartbeatReq(Rest, Key bsr 3, 0, TrUserData);
      5 -> skip_32_heartbeatReq(Rest, 0, 0, TrUserData)
    end;
dg_read_field_def_heartbeatReq(<<>>, 0, 0, _) ->
    #heartbeatReq{}.

skip_varint_heartbeatReq(<<1:1, _:7, Rest/binary>>, Z1,
			 Z2, TrUserData) ->
    skip_varint_heartbeatReq(Rest, Z1, Z2, TrUserData);
skip_varint_heartbeatReq(<<0:1, _:7, Rest/binary>>, Z1,
			 Z2, TrUserData) ->
    dfp_read_field_def_heartbeatReq(Rest, Z1, Z2,
				    TrUserData).

skip_length_delimited_heartbeatReq(<<1:1, X:7,
				     Rest/binary>>,
				   N, Acc, TrUserData)
    when N < 57 ->
    skip_length_delimited_heartbeatReq(Rest, N + 7,
				       X bsl N + Acc, TrUserData);
skip_length_delimited_heartbeatReq(<<0:1, X:7,
				     Rest/binary>>,
				   N, Acc, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_heartbeatReq(Rest2, 0, 0,
				    TrUserData).

skip_group_heartbeatReq(Bin, FNum, Z2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_heartbeatReq(Rest, 0, Z2,
				    TrUserData).

skip_32_heartbeatReq(<<_:32, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    dfp_read_field_def_heartbeatReq(Rest, Z1, Z2,
				    TrUserData).

skip_64_heartbeatReq(<<_:64, Rest/binary>>, Z1, Z2,
		     TrUserData) ->
    dfp_read_field_def_heartbeatReq(Rest, Z1, Z2,
				    TrUserData).

d_enum_LOGINMSG(1) -> 'SUCCESED';
d_enum_LOGINMSG(2) -> 'FAILED';
d_enum_LOGINMSG(3) -> 'NOTFOUND';
d_enum_LOGINMSG(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) -> merge_msgs(Prev, New, []).

merge_msgs(Prev, New, Opts)
    when element(1, Prev) =:= element(1, New) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Prev of
      #loginResp{} ->
	  merge_msg_loginResp(Prev, New, TrUserData);
      #worldResp{} ->
	  merge_msg_worldResp(Prev, New, TrUserData);
      #loginReq{} ->
	  merge_msg_loginReq(Prev, New, TrUserData);
      #helloReq{} ->
	  merge_msg_helloReq(Prev, New, TrUserData);
      #heartbeatResp{} ->
	  merge_msg_heartbeatResp(Prev, New, TrUserData);
      #heartbeatReq{} ->
	  merge_msg_heartbeatReq(Prev, New, TrUserData)
    end.

merge_msg_loginResp(#loginResp{user_id = PFuser_id,
			       user_name = PFuser_name},
		    #loginResp{result = NFresult, user_id = NFuser_id,
			       user_name = NFuser_name},
		    _) ->
    #loginResp{result = NFresult,
	       user_id =
		   if NFuser_id =:= undefined -> PFuser_id;
		      true -> NFuser_id
		   end,
	       user_name =
		   if NFuser_name =:= undefined -> PFuser_name;
		      true -> NFuser_name
		   end}.

merge_msg_worldResp(#worldResp{msg = PFmsg},
		    #worldResp{msg = NFmsg}, _) ->
    #worldResp{msg =
		   if NFmsg =:= undefined -> PFmsg;
		      true -> NFmsg
		   end}.

merge_msg_loginReq(#loginReq{},
		   #loginReq{cookie = NFcookie}, _) ->
    #loginReq{cookie = NFcookie}.

merge_msg_helloReq(#helloReq{msg = PFmsg},
		   #helloReq{msg = NFmsg}, _) ->
    #helloReq{msg =
		  if NFmsg =:= undefined -> PFmsg;
		     true -> NFmsg
		  end}.

merge_msg_heartbeatResp(#heartbeatResp{unixtime =
					   PFunixtime},
			#heartbeatResp{unixtime = NFunixtime}, _) ->
    #heartbeatResp{unixtime =
		       if NFunixtime =:= undefined -> PFunixtime;
			  true -> NFunixtime
		       end}.

merge_msg_heartbeatReq(_Prev, New, _TrUserData) -> New.


verify_msg(Msg) -> verify_msg(Msg, []).

verify_msg(Msg, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #loginResp{} ->
	  v_msg_loginResp(Msg, [loginResp], TrUserData);
      #worldResp{} ->
	  v_msg_worldResp(Msg, [worldResp], TrUserData);
      #loginReq{} ->
	  v_msg_loginReq(Msg, [loginReq], TrUserData);
      #helloReq{} ->
	  v_msg_helloReq(Msg, [helloReq], TrUserData);
      #heartbeatResp{} ->
	  v_msg_heartbeatResp(Msg, [heartbeatResp], TrUserData);
      #heartbeatReq{} ->
	  v_msg_heartbeatReq(Msg, [heartbeatReq], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-dialyzer({nowarn_function,v_msg_loginResp/3}).
v_msg_loginResp(#loginResp{result = F1, user_id = F2,
			   user_name = F3},
		Path, _) ->
    v_enum_LOGINMSG(F1, [result | Path]),
    if F2 == undefined -> ok;
       true -> v_type_uint64(F2, [user_id | Path])
    end,
    if F3 == undefined -> ok;
       true -> v_type_string(F3, [user_name | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_worldResp/3}).
v_msg_worldResp(#worldResp{msg = F1}, Path, _) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [msg | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_loginReq/3}).
v_msg_loginReq(#loginReq{cookie = F1}, Path, _) ->
    v_type_string(F1, [cookie | Path]), ok.

-dialyzer({nowarn_function,v_msg_helloReq/3}).
v_msg_helloReq(#helloReq{msg = F1}, Path, _) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [msg | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_heartbeatResp/3}).
v_msg_heartbeatResp(#heartbeatResp{unixtime = F1}, Path,
		    _) ->
    if F1 == undefined -> ok;
       true -> v_type_uint32(F1, [unixtime | Path])
    end,
    ok.

-dialyzer({nowarn_function,v_msg_heartbeatReq/3}).
v_msg_heartbeatReq(#heartbeatReq{}, _Path, _) -> ok.

-dialyzer({nowarn_function,v_enum_LOGINMSG/2}).
v_enum_LOGINMSG('SUCCESED', _Path) -> ok;
v_enum_LOGINMSG('FAILED', _Path) -> ok;
v_enum_LOGINMSG('NOTFOUND', _Path) -> ok;
v_enum_LOGINMSG(V, Path) when is_integer(V) ->
    v_type_sint32(V, Path);
v_enum_LOGINMSG(X, Path) ->
    mk_type_error({invalid_enum, 'LOGINMSG'}, X, Path).

-dialyzer({nowarn_function,v_type_sint32/2}).
v_type_sint32(N, _Path)
    when -2147483648 =< N, N =< 2147483647 ->
    ok;
v_type_sint32(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, sint32, signed, 32},
		  N, Path);
v_type_sint32(X, Path) ->
    mk_type_error({bad_integer, sint32, signed, 32}, X,
		  Path).

-dialyzer({nowarn_function,v_type_uint32/2}).
v_type_uint32(N, _Path) when 0 =< N, N =< 4294967295 ->
    ok;
v_type_uint32(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, uint32, unsigned,
		   32},
		  N, Path);
v_type_uint32(X, Path) ->
    mk_type_error({bad_integer, uint32, unsigned, 32}, X,
		  Path).

-dialyzer({nowarn_function,v_type_uint64/2}).
v_type_uint64(N, _Path)
    when 0 =< N, N =< 18446744073709551615 ->
    ok;
v_type_uint64(N, Path) when is_integer(N) ->
    mk_type_error({value_out_of_range, uint64, unsigned,
		   64},
		  N, Path);
v_type_uint64(X, Path) ->
    mk_type_error({bad_integer, uint64, unsigned, 64}, X,
		  Path).

-dialyzer({nowarn_function,v_type_string/2}).
v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(lists:append(lists:join(".",
					 lists:map(fun atom_to_list/1,
						   lists:reverse(PathR))))).


-compile({inline,id/2}).
id(X, _TrUserData) -> X.


get_msg_defs() ->
    [{{enum, 'LOGINMSG'},
      [{'SUCCESED', 1}, {'FAILED', 2}, {'NOTFOUND', 3}]},
     {{msg, loginResp},
      [#field{name = result, fnum = 1, rnum = 2,
	      type = {enum, 'LOGINMSG'}, occurrence = required,
	      opts = []},
       #field{name = user_id, fnum = 2, rnum = 3,
	      type = uint64, occurrence = optional, opts = []},
       #field{name = user_name, fnum = 3, rnum = 4,
	      type = string, occurrence = optional, opts = []}]},
     {{msg, worldResp},
      [#field{name = msg, fnum = 1, rnum = 2, type = string,
	      occurrence = optional, opts = []}]},
     {{msg, loginReq},
      [#field{name = cookie, fnum = 1, rnum = 2,
	      type = string, occurrence = required, opts = []}]},
     {{msg, helloReq},
      [#field{name = msg, fnum = 1, rnum = 2, type = string,
	      occurrence = optional, opts = []}]},
     {{msg, heartbeatResp},
      [#field{name = unixtime, fnum = 1, rnum = 2,
	      type = uint32, occurrence = optional, opts = []}]},
     {{msg, heartbeatReq}, []}].


get_msg_names() ->
    [loginResp, worldResp, loginReq, helloReq,
     heartbeatResp, heartbeatReq].


get_group_names() -> [].


get_msg_or_group_names() ->
    [loginResp, worldResp, loginReq, helloReq,
     heartbeatResp, heartbeatReq].


get_enum_names() -> ['LOGINMSG'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
      Es when is_list(Es) -> Es;
      error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def(loginResp) ->
    [#field{name = result, fnum = 1, rnum = 2,
	    type = {enum, 'LOGINMSG'}, occurrence = required,
	    opts = []},
     #field{name = user_id, fnum = 2, rnum = 3,
	    type = uint64, occurrence = optional, opts = []},
     #field{name = user_name, fnum = 3, rnum = 4,
	    type = string, occurrence = optional, opts = []}];
find_msg_def(worldResp) ->
    [#field{name = msg, fnum = 1, rnum = 2, type = string,
	    occurrence = optional, opts = []}];
find_msg_def(loginReq) ->
    [#field{name = cookie, fnum = 1, rnum = 2,
	    type = string, occurrence = required, opts = []}];
find_msg_def(helloReq) ->
    [#field{name = msg, fnum = 1, rnum = 2, type = string,
	    occurrence = optional, opts = []}];
find_msg_def(heartbeatResp) ->
    [#field{name = unixtime, fnum = 1, rnum = 2,
	    type = uint32, occurrence = optional, opts = []}];
find_msg_def(heartbeatReq) -> [];
find_msg_def(_) -> error.


find_enum_def('LOGINMSG') ->
    [{'SUCCESED', 1}, {'FAILED', 2}, {'NOTFOUND', 3}];
find_enum_def(_) -> error.


enum_symbol_by_value('LOGINMSG', Value) ->
    enum_symbol_by_value_LOGINMSG(Value).


enum_value_by_symbol('LOGINMSG', Sym) ->
    enum_value_by_symbol_LOGINMSG(Sym).


enum_symbol_by_value_LOGINMSG(1) -> 'SUCCESED';
enum_symbol_by_value_LOGINMSG(2) -> 'FAILED';
enum_symbol_by_value_LOGINMSG(3) -> 'NOTFOUND'.


enum_value_by_symbol_LOGINMSG('SUCCESED') -> 1;
enum_value_by_symbol_LOGINMSG('FAILED') -> 2;
enum_value_by_symbol_LOGINMSG('NOTFOUND') -> 3.


get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> 'common.proto'.



gpb_version_as_string() ->
    "4.1.6".

gpb_version_as_list() ->
    [4,1,6].
