%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.1

-ifndef(common_pb).
-define(common_pb, true).

-define(common_pb_gpb_version, "4.10.1").

-ifndef('LOGINREQ_PB_H').
-define('LOGINREQ_PB_H', true).
-record(loginReq,
        {cookie = <<>>          :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('LOGINRESP_PB_H').
-define('LOGINRESP_PB_H', true).
-record(loginResp,
        {result = 'FAILED'      :: 'FAILED' | 'SUCCEEDED' | 'NOTFOUND' | integer() | undefined, % = 1, enum LoginStatus
         user_id = 0            :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('HELLOREQ_PB_H').
-define('HELLOREQ_PB_H', true).
-record(helloReq,
        {msg = <<>>             :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('WORLDRESP_PB_H').
-define('WORLDRESP_PB_H', true).
-record(worldResp,
        {msg = <<>>             :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('HEARTBEATREQ_PB_H').
-define('HEARTBEATREQ_PB_H', true).
-record(heartbeatReq,
        {
        }).
-endif.

-ifndef('HEARTBEATRESP_PB_H').
-define('HEARTBEATRESP_PB_H', true).
-record(heartbeatResp,
        {unixtime = 0           :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
